AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Naming/AsciiIdentifiers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $driver